id: 10000103
key: "xilonen"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NATLAN
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Xilonen"
stats: {
   base_hp: 965.713134765625
   base_atk: 21.4130001068115
   base_def: 72.3943023681641
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 828.01171875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 62.0730018615723
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.3583698272705
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1416.33581542969,
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 106.17749786377,
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 31.4024753570557
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.09
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2200.76806640625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 164.983505249023
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.7946166992188
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2789.09204101563
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 209.087997436523
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.8387184143066
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3377.41625976563
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 253.192504882813
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.8828277587891
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.27
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3965.740234375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 297.296997070313
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.9269332885742
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.36
      }
   }
}
skill_details: {
   skill: 10382
   burst: 10385
   attack: 10381
   burst_energy_cost: 60
}
name_text_hash_map: 4197635682
