id: 10000096
key: "arlecchino"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_FATUI
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Arlecchino"
stats: {
   base_hp: 1020
   base_atk: 26.62660026550293
   base_def: 59.53
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51.05
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.82823371887207
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 14.96
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.32
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.04829406738281
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2324
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 135.68
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.67504119873047
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.19200000166893005
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2945
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.95
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.89510345458984
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.19200000166893005
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3567
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.222
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.11516571044922
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.2879999876022339
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4188
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 244.49
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 109.3352279663086
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.3840000033378601
      }
   }
}
skill_details: {
   skill: 10018
   burst: 10019
   attack: 10024
   burst_energy_cost: 60
}
name_text_hash_map: 1006042610
