id: 10000096
key: "arlecchino"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_FATUI
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Arlecchino"
stats: {
   base_hp: 1020.0524291992188
   base_atk: 26.62660026550293
   base_def: 59.53084945678711
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 874.6027221679688
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51.04349899291992
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.82823371887207
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1496.0308837890625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.31124877929688
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.04829406738281
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2324.601806640625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 135.66824340820312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.67504119873047
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.19200000166893005
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2946.030029296875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.93600463867188
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.89510345458984
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.19200000166893005
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3567.45849609375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.20375061035156
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.11516571044922
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.2879999876022339
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4188.88671875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 244.47149658203125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 109.3352279663086
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.3840000033378601
      }
   }
}
skill_details: {
   skill: 10962
   burst: 10965
   attack: 10961
   burst_energy_cost: 60
}
name_text_hash_map: 167199474
