id: 10000102
key: "mualani"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Mualani"
stats: {
   base_hp: 1182.1168212890625
   base_atk: 14.1512002944946
   base_def: 44.3938598632813
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1013.5582885742188
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38.0646018981934
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.1324882507324
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1733.7181396484375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.1104965209961
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.7529392242432
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.0480000004172
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2693.93115234375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.1716995239258
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.2468757629395
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.0960000008345
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3414.091064453125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.2176055908203
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.8673286437988
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.0960000008345
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4134.2509765625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.2635040283203
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 49.4877815246582
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.1439999938011
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4854.41064453125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.3094024658203
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.1082305908203
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.1920000016689
      }
   }
}
skill_details: {
   skill: 10872
   burst: 10875
   attack: 10871
   burst_energy_cost: 60
}
name_text_hash_map: 1504902330
